- storage/tianmu/core/engine.cpp
> struct HASH trans to collation_unordered_map #7

- storage/tianmu/core/column_bin_encoder.cpp
- storage/tianmu/core/engine.cpp
- storage/tianmu/types/rc_data_types.h
1. flag is changed to is_flag_set by m8
2. name -> m_coll_name CHARSET_INFO(include/m_ctype.h) from strings/CHARSET_INFO.txt
> core, types: Structures and fields have been adjusted by MySQL8

- storage/tianmu/core/engine.cpp
- storage/tianmu/core/engine_execute.cpp
- storage/tianmu/core/rc_table.cpp
SELECT_LEX_UNIT -> Query_expression
SELECT_LEX -> Query_block
select_lex -> query_block
all_selects_list -> all_query_blocks_list
> lex have been adjusted by MySQL 8.0

- storage/tianmu/core/engine.cpp
- storage/tianmu/core/item_tianmu_field.cpp
- storage/tianmu/core/mysql_expression.cpp
> NOT_FIXED_DEC change to DECIMAL_NOT_SPECIFIED #7

- include/mysys_err.h
- sql/handler.h
- sql/lex.h
- sql/query_options.h
- sql/sql_exchange.h
- sql/sql_yacc.yy
1.add ROUGHLY parse
2.add HA_NON_KEY_AUTO_INC、DB_TYPE_TIANMU
> sql: add func from tiamnu

- storage/tianmu/core/engine.cpp
init_one_table deleted
global_query_id change to atomic_global_query_id
MY_KEEP_PREALLOC deleted
> core/engine: fix variable and api error by MySQL8

- sql/mysqld.h
- storage/tianmu/common/mysql_gate.h
- storage/tianmu/core/engine.cpp
> core/engine: fix ER and api

- sql/sql_lex.cc
- sql/sql_lex.h
- sql/sql_optimizer.h
- storage/tianmu/core/engine_execute.cpp
- storage/tianmu/core/query_compile.cpp
> Fix engine_execute #51

- sql/item.h
- storage/tianmu/common/mysql_gate.h
- storage/tianmu/core/engine.cpp
- storage/tianmu/core/engine_results.cpp
- storage/tianmu/core/item_tianmu_field.cpp
- storage/tianmu/core/item_tianmu_field.h
- storage/tianmu/core/mysql_expression.cpp
1.Item：str_value protected to public
2.TODO: fields need convert List<Item> to mem_root_deque<Item *>
3.datetime_to_timeval()  parameter change
4.timeval to my_timeval
5.string_field_type() parameter change
6.int_type to get_interval_type()
7.date_sub_interval to is_subtract()
> fix: Item、api、type、add TODO by MySQL8

- sql/item.h
- storage/tianmu/core/query.cpp
- storage/tianmu/core/query_compile.cpp
result_field -> get_result_field()
> fix: Item: add get_result_field()

- storage/tianmu/core/engine_execute.cpp
comment follows:
1. thd->fill_derived_tables() && lex->derived_tables
2. sl->braces
3. about  List< Item > -> mem_root_deque<Item *>
> core/engine_execute: comments out some codes that need TODO #51

- storage/tianmu/core/query_compile.cpp
1. get_arg_count() -> arg_count
2. ORDER::ORDER_ASC -> ORDER_ASC
> core/query_compile: fix api from m8

- storage/tianmu/core/rcattr_exeq_rs.cpp
- storage/tianmu/core/temp_table.cpp
1. instr()->strstr()
2. ORDER::ORDER_NOT_RELEVANT -> ORDER_NOT_RELEVANT
> core/*: fix api by MySQL 8.0

- storage/tianmu/handler/tianmu_handler.cpp
real_maybe_null() -> is_nullable()
TABLE:status -> m_status private
HA_EXTRA_NO_CACHE is deleted
register_query_cache_table is deleted
> handler/tianmu_handler: fix Field、TABLE、api by MySQL8

- storage/tianmu/loader/load_parser.cpp
wrote_create_file->logged_data_file from struct LOAD_FILE_INFO
> loader/load_parser.cpp: fix field by MySQL 8.0

- storage/tianmu/handler/tianmu_handler_com.cpp
- storage/tianmu/system/configuration.cpp
- storage/tianmu/system/configuration.h
> fix:CONFIG:char to bool、 MYSQL_VAR

- storage/tianmu/handler/tianmu_handler_com.cpp
- storage/tianmu/system/configuration.cpp
- storage/tianmu/system/configuration.h
st_mysql_sys_var -> SYS_VAR
st_mysql_show_var -> SHOW_VAR
THD:no_errors is deleted
total_ha is deleted
mysql_declare_plugin is updated
> handler/tianmu_handler_com: fix SYS_VAR、SHOW_VAR、API by MySQL8.0

- storage/tianmu/types/rc_item_types.cpp
my_decimal2string input args are changed
> types/rc_item_types.cpp: string2my_decimal is deleted by MySQL 8.0

- storage/tianmu/index/rc_table_index.cpp
> index/rc_table_index.cpp: fix api by MySQL 8.0

- storage/tianmu/index/kv_store.h
> index/kv_store: fix condition_variable not declared

- cmake/maintainer.cmake
> tianmu compile: fix -Werror #101

- sql/handler.cc
- sql/mysqld.cc
- sql/mysqld.h
- storage/tianmu/core/engine.cpp
tianmu storage engine slot is incorrect. fix it.
>  fix(sql, tianmu): fix tianmu storage engine slot is incorrect. (#115)

- sql/sql_load.cc
- storage/tianmu/core/engine.cpp
1.  add tianmu's load function tianmu_load   in sql/sql_load.cc;
2.  initialize LOAD_FILE_INFO info to tianmu_load;
> feat(sql): support mysql_load. (#8)

- scripts/my.cnf.sample
1. add my.cnf.sample to script directory;
2. user can use sed -i 's/YOUR_ABS_PATH/yourpath/g' my.cnf.sample; then mv my.cnf.sample my.cnf;
> feat(my.cnf): add my.cnf.sample file. (#120)
